### ISSUE TITLE
Can some one explain this sequence of messages? I am not able to follow

### ISSUE THREAD

**Issue by kancpandian** [githubschool/open-enrollment-classes-introduction-to-github#1230]
## Adding <your-city> to the map

Hi everyone! This issue is to track the addition of <your-city> to the map, which can be found at:
- Longitude: <your-longitude>
- Latitude: <your-latitude>

**Comment by crichID** [comment]
@kancpandian I'm not sure if I understand your question, but let me try to do my best:

1. The first comment you created on #927 was to be added as a collaborator to this repository. This is something that would typically be done using the Settings for the repository or the organization. But since this is an open course, we are doing it with this issue.
2. The second task was to create this issue. Typically, when we begin work on a new project, it is because we have had a conversation about a new feature we would like to add or a bug we need to fix. Those conversations happen in issues.
3. When you make the actual changes to the code, you will open a pull request. The pull request is a discussion about the actual changes you are making. When you merge the pull request, you will also close this issue since the new file will have been added to the repository! 

I hope this helps!
