### ISSUE TITLE
Add ;) 

### ISSUE THREAD

**Issue by zaticpetru** [githubschool/open-enrollment-classes-introduction-to-github#19185]
Hello! :wave: Please add me as a collaborator to this repo. 

47°01'10.6"N 
28°45'00.8"E

**Comment by Alli666Mirdad** [comment]
I have some little bit problems here with the thieves and Liar group honey
and my internet connection was poor right now.
I'm so sorry to say cause I can't help you all right now.. I'm just until
one off the thieves, stealing and Liar people meet and paying me 50 in
cash. Then I will released all web that I hold, and I will help who's need
a helping from me. And I will start doing my web work again because I'm
shames and so embarrassed after they write so many bad and crazy things
about me in they blog and News Journal. I'm so embarrassed. where I can
keep my face??
