### ISSUE TITLE
I need help: file number to close for pull request

### ISSUE THREAD

**Issue by dstanner** [githubschool/open-enrollment-classes-introduction-to-github#20105]
I created my .json file in my branch to put my pin on the map. But now I'm following the instruction and trying to create a pull request for it. The instructions to say to use the keyword "closes" followed by the commit number.  I don't know where to find the commit number.  I can find my file by searching the files in my branch, but I can't find the number associated with it to add to the pull request.

Help appreciated.

**Comment by dmartira** [comment]
Did you find it? Light Grey # listed after the title?

**Comment by dstanner** [comment]
After the title of my file? i.e., the name of the file?  I don't any number.  Just a hex-looking code (27e0e76).

**Comment by NFogell** [comment]
There's a couple of ways to view it:  
- If you type "closes #" then a list should pop up, and your issue should be one on that list.  The title of 
   your issue is "Adding a new user here", I think, so you can click on that and it will insert the number.
- If you click on the issues tab you can see the list of issues, and yours is towards the top of the list.  There's a number, #.... underneath the title, which is the one you want.

**Comment by dstanner** [comment]
Ahh! I didn't realize it was to be tied to the "add new user" issue -- I missed that somehow.  Thanks!
