### ISSUE TITLE
Adding Hood River, OR to the map

### ISSUE THREAD

**Issue by ktfeucht** [githubschool/open-enrollment-classes-introduction-to-github#69]
## Adding Hood River, OR to the map

Hi everyone! This issue is to track the addition of Hood River, OR to the map, which can be found at:

- Longitude: -121.521462 
- Latitude: 45.705397

**Comment by crichID** [comment]
:wave: @ktfeucht it looks like your Pull request has been merged, but it did not close the issue. It is probably because your forgot to add the special key words GitHub was looking for or added extra words between the magic words and the issue number. The magic words include `fix`, `fixes`, `fixed`, `close`, `closes`, `closed`, `resolve`, `resolves`, `resolved` + the Issue number. So your PR would have looked something like this `This Pull Request resolves #69`. I will go ahead and close this issue since it looks like you have successfully added your pin to the map! 

Welcome to GitHub!
